### ISSUE TITLE
attribute is named differently between mbed cloud portal and javascript sdk

### ISSUE THREAD

**Issue by mbanders** [ARMmbed/mbed-cloud-sdk-javascript#229]
In the mbed cloud portal at https://portal.us-east-1.mbedcloud.com/ we login, click on a device, and click the "Attributes" tab. There is an attribute named `endpoint_type`, and no attribute named `device_type`.

However, when we use mbed-cloud-sdk v1.2.8 and do `connect.listConnectedDevices()` those devices have an attribute named `deviceType`, and no attribute named `endpointType`.

Basically the value of the cloud portal's `endpoint_type` matches the value of the javascript sdk's `deviceType`. Is this change of name a bug? It certainly confused us for a bit today. And if it is a bug, is it a bug with the cloud portal or the javascript sdk?

**Comment by mray19027** [comment]
Clarification to @mbanders issue:

<h3>Mbed Cloud Client sets both endpoint and device type.</h3>

Endpoint type (set at [mbed_cloud_client_user_config.h](https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/mbed_cloud_client_user_config.h#L23)):
```
#define MBED_CLOUD_CLIENT_ENDPOINT_TYPE         "default"
```

Device type (set at [mbed_cloud_dev_credentials.c](https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/mbed_cloud_dev_credentials.c#L44)):
```
const char MBED_CLOUD_DEV_DEVICE_TYPE[] = "dev_device_type";
```

<h3>Mbed Cloud Portal queries on endpoint type</h3>

In the attribute tab of a connected device, endpoint type shows `default`. Querying for devices or setting up device filters all use endpoint type.

<h3>Mbed Cloud SDKs incorrectly use device type instead of endpoint type</h3>

When using the SDK to query for devices or set up a device filter, the SDK uses the language `device type`, when in reality it is querying on endpoint type.

Example:

`DeviceObject` has data member `deviceType` in [/deviceDirectory/types.ts](https://github.com/ARMmbed/mbed-cloud-sdk-javascript/blob/master/src/deviceDirectory/types.ts#L47)

[Documentation ](https://cloud.mbed.com/docs/current/mbed-cloud-sdk-javascript/interfaces/devicelistoptions.html) says this is an available query.

Both instances need to have the language changed from device type to endpoint type because the SDK is actually querying endpoint type, not device type.

**Comment by mbanders** [comment]
Looks like the different name (cloud's "endpoint_type" to javascript sdk's "deviceType") was set in this commit https://github.com/ARMmbed/mbed-cloud-sdk-javascript/pull/93/files by @thegecko 

It's confusing because in mbed cloud if you click on a device and then on "Live resources" tab there is a separate "Device Type" at "/3/0/17" but that's different. It has a different value, it's set differently. Not an attribute.

**Comment by mray19027** [comment]
@alexl0gan Any feedback on this?

**Comment by acabarbaye** [comment]
Hi all,

This is not a bug but the result of a deliberate choice to rename some fields in the SDK to ensure consistency across the different services that are used e.g. endpoint-name <-> device id, connected <-> registered, etc. . These changes are the same in all the SDKs we publish (i.e. python, Java, .Net). Portal aims at using the SDKs in the near future so discrepancies between the Portal and the SDKs should disappear with time. At the same time, the SDK will soon let the user be able to call the REST APIs directly if he or she wants. 
Regarding the difference between device Type as a LWM2M resource and device Type/endpoint type as a field sent back from the Cloud, I am not quite sure why there is one as they are essentially  the same things. I will contact the different team in charge to understand the rationale between the distinction. 

Hope I clarified the situation.
